### PR TITLE
Improve compatibility with mods that modify the pump recipe or tech

### PR DESCRIPTION
**Pull request by branan**
Previously, whether or not this mod would pick up other mods would depend on the loading order, which is not well-defined by Factorio.

This change updates the mod to wait until a later loading phase to choose its unlock technology and recipe ingredients, which should make it more robust at interoperating with other mods when the load order changes.

This also adds explicit support for pyindustry, so that the `configurable-valve` will end up in the same tech node and with the same ingredients as the `py-{over,under}flow-valve` recipes.

### CODE REVIEW

**Comment by branan** [comment]
For me, this was needed to get the valve to show up in the technology that Py moves pumps to. Otherwise it ended up in `fluid-handling`, which is much later in the Py tech tree (post-circuits).

This would probably also work in `data-updates`. I am not a particularly experienced Factorio modder, so I am happy with whatever you think makes sense ¯\\\_(ツ)_/¯

**Comment by branan** [comment]
I've done a bit more poking around and thinking since I opened this.

It looks like in Py the valves are _supposed_ to be unlocked in `fluid-handling`. That happened by accident here due to the mod load order meaning that this mod didn't see that Py had moved the pumps to a different tech. Therefore I think this PR is still correct to ensure that this mod behaves correctly in the face of "mods messing with pumps".

It does need some supplementing to get integration with Py working:

Either PyIndustry needs an optional dependency on this mod to adjust the unlock&recipe, or this mod needs an optional dep on PyIndustry to switch its recipe/unlock to match `py-check-valve` rather than `pump`. (Or a third mod needs to be created that integrates this mod with Py)

**Comment by heinwessels** [comment]
Hello! This a good addition! I have a few thoughts:

- Earlier in the load order is always better, so I think `data-updates.lua` is the better place.
- For Py aligning it with the check-valve sounds like a better idea. In that case I will add special compat for Py also in data-updates.lua

I'm gonna try get to this in the next few days hopefully and then merge your PR in whatever state it is, and add the remaining code required. You're also welcome to try yourself.

Thanks for the PR!

**Comment by branan** [comment]
I think it'll just a few lines of code to add the Py compat, I'll give it a try this afternoon and update the PR

**Pull request merged**
